name: Release

on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    if: github.repository == 'chancestrickland/harmonious'

    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # This makes action fetch all Git history so that Changesets can
          # generate changelogs with the correct commits
          fetch-depth: 0

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          version: 12.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Create release pull request or publish to npm
        uses: changesets/action@master
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Change generated release intent
        uses: ./.github/actions/change-release-intent
